### ISSUE TITLE
Legacy features

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [nickcharlton/dokku-cookbook#1]
Do you have any plan for porting the features from the legacy dokku-cookbook?

**Comment by nickcharlton** [comment]
For certain parts, yes.

So far I'm planning on introducing an LWRP for apps and plugins. But, I'm keen on avoiding the source install until after I've done a 1.0.0 release, which will probably happen after then.

Is there something specific you're hoping for?

**Comment by SharpEdgeMarshall** [comment]
I'm still learning Chef and deciding if it's a good choice for deployment, but in case it would be great having LWRP for apps.

Instead i think that plugins LWRP is a must for configuring the server correctly on the fly.

**Comment by nickcharlton** [comment]
Great. Plugins is first on my list at the moment, followed by apps.
